version: "3"

services:
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    networks:
      - backend
  redis:
    image: redis:3.2-alpine
    ports:
      - "6739:6739"
    volumes:
      - "./redis/data:/data"
    networks:
      - backend
  cassandra:
    image: cassandra:3.10
    ports:
      - "9042:9042"
    volumes:
      - "./cassandra/data:/var/lib/cassandra"
    networks:
      - backend
  hive:
    image sishihara/hive:
  minio:
    image: minio/minio:latest
    command: server /export
    ports:
      - "9000:9000"
    volumes:
      - "./minio/data/export:/export"
    networks:
      - backend
  hive:
    image: sishihara/hive:latest
    ports:
      - "9083:9083"
      - "10000:10000"
    networks:
      - backend
  presto:
    image: passant/presto:0.170
    ports:
      - "8080:8080"
    volumes:
      - "./presto/data:/var/presto/data"
      - "./presto/etc/catalog:/opt/presto/etc/catalog"
    networks:
      - backend

networks:
  backend:
